import { NgModule } from '@angular/core';
import {
  MatInputModule,
  MatIconModule,
  MatProgressBarModule,
  MatCardModule,
  MatToolbarModule,
  MatSelectModule,
  MatOptionModule,
  MatButtonModule,
  MatMenuModule,
  MatCheckboxModule,
  MatRadioModule,
  MatTableModule,
  MatSortModule,
  MatPaginatorModule,
  MatSnackBarModule,
  MatDialogModule,
  MatTooltip,
  MatTooltipModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatButtonToggleModule, 
  MatDividerModule, 
  MatGridListModule
} from '@angular/material';

import { ScrollingModule } from '@angular/cdk/scrolling';
import { CdkStepperModule } from '@angular/cdk/stepper';
import { CdkTableModule } from '@angular/cdk/table';
import { CdkTreeModule } from '@angular/cdk/tree';

@NgModule({
  imports: [MatNativeDateModule,
    MatDatepickerModule,
    CdkTreeModule,
    CdkTableModule,
    ScrollingModule,
    CdkStepperModule,
    MatRadioModule,
    MatInputModule,
    MatIconModule,
    MatProgressBarModule,
    MatCardModule,
    MatToolbarModule,
    MatSelectModule,
    MatOptionModule,
    MatButtonModule,
    MatCheckboxModule,
    CdkTableModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatIconModule,
    MatInputModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSelectModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatMenuModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatButtonToggleModule, 
    MatDividerModule, 
    MatGridListModule
  ],
  exports: [MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    CdkTreeModule,
    CdkTableModule,
    ScrollingModule,
    CdkStepperModule,
    MatRadioModule,
    MatInputModule,
    MatIconModule,
    MatProgressBarModule,
    MatCardModule,
    MatSelectModule,
    MatOptionModule,
    MatButtonModule,
    MatMenuModule,
    MatCheckboxModule,
    CdkTableModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatIconModule,
    MatInputModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSelectModule,
    MatToolbarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatSnackBarModule,
    MatDialogModule,
    MatButtonToggleModule, 
    MatDividerModule, 
    MatGridListModule
  ]
})
export class MaterialModule { }
